name: Intergration continue
on:
  push:
    branches: [ publish ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2', '8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          tools: castor
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Build and Start Containers
        run: docker compose -f "docker-compose.yml" up -d --build
      
      - name: Wait for Database to be ready
        run: |
          echo "Waiting for PostgreSQL to accept connections..."
          for i in {1..30}; do
            docker exec $(docker ps -qf "ancestor=postgres:16-alpine") pg_isready -U postgres && break
            echo "Postgres not ready yet..."
            sleep 1
          done
      
      - name: Symfony setup and migration
        run: |
          composer install
          php bin/console doctrine:database:drop -f --if-exists --env=test
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate -n --env=test
          php bin/console doctrine:fixtures:load -n --purge-with-truncate --env=test
          php bin/console sass:build
      - name: Tests
        run: php bin/phpunit
      - name: Analysis
        run: php vendor/bin/phpstan